# Generated by Django 5.0.7 on 2024-09-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgalery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGalery',
            new_name='ProductGallery',
        ),
    ]
